spring:
  datasource:
    # MySQL 기본 설정
    url: jdbc:mysql://localhost:3306/rolling_db?useUnicode=true&characterEncoding=euckr
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: gkdms~!1357
  jpa:
    database: mysql # MySQL 상세 지정
    show-sql: true # API 호출 시 sql문을 출력
    properties:
      hibernate:
        format_sql: true
        ddl-auto: nones
    defer-datasource-initialization: true
  security:
    user:
      name: user
      password: 1111
